---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: alpine

inputs:
- name: api

outputs:
- name: reports

run:
  dir: api
  path: sh
  args:
  - -exc
  - |
    go test test/ > ../reports/api-report.html
