---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: alpine

inputs:
- name: api

outputs:
- name: reports

run:
  dir: api
  path: sh
  args:
  - -exc
  - |
    pwd
    ls -l
    go test api/test/server_test.go > .reports/api-report.html
