---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: alpine

inputs:
- name: api

outputs:
- name: reports

run:
  path: sh
  args:
  - -exc
  - |
    go test api/test/ > reports/api-report.html
